"""initial schema

Revision ID: 1fa856b3969a
Revises: 
Create Date: 2026-06-17 10:57:32.525175

"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fa856b3969a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organisation_slug'), 'organisation', ['slug'], unique=True)
    op.create_table('person',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=200), nullable=False),
    sa.Column('roll', sa.String(length=200), nullable=False),
    sa.Column('initialer', sa.String(length=8), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('support_function',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('namn', sa.String(length=120), nullable=False),
    sa.Column('ikon', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_function_key'), 'support_function', ['key'], unique=True)
    op.create_table('dialogue',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organisation_id', sa.Integer(), nullable=False),
    sa.Column('ansvarig_chef_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('skapad_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ansvarig_chef_id'], ['person.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kpi_area',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('namn', sa.String(length=160), nullable=False),
    sa.Column('short', sa.String(length=32), nullable=True),
    sa.Column('ikon', sa.String(length=64), nullable=False),
    sa.Column('lower_better', sa.Boolean(), nullable=False),
    sa.Column('support_function_id', sa.Integer(), nullable=False),
    sa.Column('ordning', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['support_function_id'], ['support_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kpi_area_key'), 'kpi_area', ['key'], unique=True)
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('support_function_id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=160), nullable=False),
    sa.Column('ordning', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['support_function_id'], ['support_function.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agreement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('kpi_area_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ansvarig', sa.String(length=200), nullable=False),
    sa.Column('klart_senast', sa.Date(), nullable=True),
    sa.Column('genomgangen', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogue.id'], ),
    sa.ForeignKeyConstraint(['kpi_area_id'], ['kpi_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dialogue_id', 'kpi_area_id', name='uq_agreement_area')
    )
    op.create_table('measurement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('kpi_area_id', sa.Integer(), nullable=False),
    sa.Column('value_text', sa.String(length=64), nullable=False),
    sa.Column('value_num', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=32), nullable=False),
    sa.Column('target_text', sa.String(length=64), nullable=False),
    sa.Column('target_num', sa.Float(), nullable=False),
    sa.Column('bar_max', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('good', 'warn', 'alert', name='status'), nullable=False),
    sa.Column('trend_dir', sa.Enum('up', 'down', name='trend_dir'), nullable=False),
    sa.Column('trend_good', sa.Boolean(), nullable=False),
    sa.Column('trend_text', sa.String(length=120), nullable=False),
    sa.Column('interpretation', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogue.id'], ),
    sa.ForeignKeyConstraint(['kpi_area_id'], ['kpi_area.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dialogue_id', 'kpi_area_id', name='uq_measurement_area')
    )
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kpi_area_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('ordning', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['kpi_area_id'], ['kpi_area.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question')
    op.drop_table('measurement')
    op.drop_table('agreement')
    op.drop_table('tool')
    op.drop_index(op.f('ix_kpi_area_key'), table_name='kpi_area')
    op.drop_table('kpi_area')
    op.drop_table('dialogue')
    op.drop_index(op.f('ix_support_function_key'), table_name='support_function')
    op.drop_table('support_function')
    op.drop_table('person')
    op.drop_index(op.f('ix_organisation_slug'), table_name='organisation')
    op.drop_table('organisation')
    # ### end Alembic commands ###
